name: rtlsdr
version: 0.0.1
homepage: https://github.com/renggli/dart-rtlsdr
description: Dart bindings for Software Defined Radio (librtlsdr).
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  ffi: ^0.1.0
  meta: ^1.2.0
  more: ^2.7.0
dev_dependencies:
  test: ^1.15.0
  mockito: ^4.1.1
